### ISSUE TITLE
Release 0.6 pre-release with tag name that makes Composer happy

### ISSUE THREAD

**Issue by dmnc** [theorchard/monolog-cascade#105]
I added this comment onto the end of a closed PR which was probably, with hindsight, rather silly: https://github.com/theorchard/monolog-cascade/pull/103#issuecomment-1117716874.

> Is anybody able to use the tag successfully? I'm having issues because of the branch alias at https://github.com/theorchard/monolog-cascade/blob/master/composer.json#L43
>
> This stops anything like dev-master#0.6.0-pre from working. I can't use 0.6.0@pre because pre isn't in the [composer list of stabilities](https://getcomposer.org/doc/articles/versions.md#stabilities).

@andymc or @mymac80 could we please have a new tag called `0.6.0-beta1`? That should then allow composer to pull it in as `"theorchard/monolog-cascade": "^0.6.0@beta"`.

Alternatively, if it's all working correctly, could it just be `0.6.0`?

**Comment by andymc** [comment]
yeah sorry about that will get to it shortly
