### ISSUE TITLE
Symfony 2.8 Update?

### ISSUE THREAD

**Issue by lightglitch** [theorchard/monolog-cascade#42]

**Comment by rantonmattei** [comment]
Upgraded to support Symfony 2.8

**Comment by glensc** [comment]
what this is about?

you should use base version in your `composer.json` what is minimum required for functionality, not bump composer deps each time dependency has new release.

perhaps you want to change your version range from `~` to `^` operator?

`"^2.7.0 | ^3.0"`

**Comment by rantonmattei** [comment]
I see, good point. I wanted to allow for more recent Symfony which was not possible with `~2.7.0`.
You're right, it should be `~2.7` or `^2.7.0`.

I will fix that.

**Comment by glensc** [comment]
`~2.7.0` is same as `~2.7`, i.e: `>=2.7.0 && <2.8`

**Comment by rantonmattei** [comment]
`~2.7.0` is not the same as `~2.7`
`~2.7.0` is `>=2.7.0` && `<2.8.0` (that was the issue, the `composer.json` had `~2.7.0` blocking higher version of Symfony)
`~2.7` is `>=2.7.0` && `<3.0.0`

`~2.7` and `^2.7.0` are equivalent though.
