### ISSUE TITLE
Replace symfony/serializer with a dedicated case-changing component

### ISSUE THREAD

**Issue by djmattyg007** [theorchard/monolog-cascade#46]
Given the only thing symonfy/serializer appears to be used for is to convert snake_case names to camelCase, it seems a bit unnecessary to require the entire serializer component for this one task. Surely a smaller, dedicated library would be more suited to the task? There are plenty of examples here: https://packagist.org/search/?q=camel

**Comment by djmattyg007** [comment]
Alternatively you could just pull out the relevant code from the symfony/serializer package and call it yourself manually, as it's only really a couple of lines of code:

    public function snakeCaseToCamelCase($unnormalizedName)
    {
        $camelCasedName = preg_replace_callback('/(^|_|\.)+(.)/', function ($match) {
            return strtoupper($match[2]);
        }, $unnormalizedName);
        return lcfirst($camelCasedName);
    }

**Comment by rantonmattei** [comment]
Shoot a PR

**Comment by denizdogan** [comment]
#67

**Comment by rantonmattei** [comment]
Thx @denizdogan !
👍
