### ISSUE TITLE
Configure log file to have 'daily' timestamp

### ISSUE THREAD

**Issue by aschwin** [theorchard/monolog-cascade#61]
Hi,

Is it possible to have 'web-2016-05-27.log' instead of just 'web.log'? Or would that be tedious?

Kind regards,

Aschwin Wesselius

**Comment by rantonmattei** [comment]
Look into https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/RotatingFileHandler.php
That should work for what you are looking for..

**Comment by aschwin** [comment]
Ah nice! Thanks, I didn't not searched good enough for it.
