### ISSUE TITLE
default namespace for handler

### ISSUE THREAD

**Issue by keywan-ghadami-oxid** [theorchard/monolog-cascade#63]
when using classname without namespace
monolog cascade should use Monolog\Handler\
e.g.

```
class: StreamHandler
```

should be the same as

```
class: Monolog\Handler\StreamHandler
```

**Comment by rantonmattei** [comment]
Unfortunately, I have to disagree on this one. You need to be able to use any handlers, not only the ones that Monolog provides out of the box.

**Comment by keywan-ghadami-oxid** [comment]
Sure you should still be able to use full qualified classnames but if the classname does not contain any backslash you can use it as shorthand for monolog handlers.
monolog bundle supports a type attribue

Type to class example:
```
if ($type) {            
       $class = '\\Monolog\\Handler\\' . $type . 'Handler';
}
```

shorthand for class attribute can be also usefull for processors.
I did something like this in my monolog configuration library:
```
$class = $processorConfig['class'];
if (strpos('\\',$class)===false){
    $class = '\\Monolog\\Processor\\' . $class;
}
```
This is only sytax suggar for the configuration file, of cause things will work fine without this feature.

**Comment by rantonmattei** [comment]
@jessmchung can you close this?
