### ISSUE TITLE
Support for monolog  "^2.0"?

### ISSUE THREAD

**Issue by tolgaulas** [theorchard/monolog-cascade#90]
Has it been tested on monolog latest version? If yes can you please update the composer.json accordingly?

**Comment by MarioDevment** [comment]
I have an error that does not allow me to advance to the latest version of monolog, otherwise it seems to work fine.

```
Argument 1 passed to Mock_TestHandler_032817aa::pushProcessor() must be callable, string given, called in /opt/project/src/Config/Loader/ClassLoader/HandlerLoader.php on line 187
 /opt/project/src/Config/Loader/ClassLoader/HandlerLoader.php:187
 /opt/project/tests/Config/Loader/ClassLoader/HandlerLoaderTest.php:263
```

**Comment by geshub** [comment]
Would be great to have support for monolog > 2.0

**Comment by opok** [comment]
guys, is this project being maintained ? Do you ever plan to support monolog > 2.0 ?
It's exactly 11 months since @tolgaulas reported this issue.

**Comment by setpill** [comment]
There are already multiple forks that implement this (MarioDevment, LinioIT). Is there a reason this is blocked?

**Comment by dmnc** [comment]
I can see a few forks but not any PRs. @MarioDevment or @klaussilveira are either of you branches in a state where they could be merged?

I'm sure @rantonmattei and @mymac80 may be able to help if we can get a PR together.

**Comment by pluc** [comment]
Still doesn't work as of August 2021

**Comment by glensc** [comment]
@pluc so instead of complaining, send your proposal for the changes in form of a pull request.

**Comment by dmnc** [comment]
All my testing indicates that 0.6 supports monolog 2 without issue. I'll send a PR to update composer.json.
